mysql:
  host: localhost
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: 051102ydq
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: ""
  bei_an: ""
  title: Askanuo 的小屋
  qq_image: ""
  version: ""
  email: ""
  wechat_image: ""
  name: ""
  job: ""
  addr: ""
  slogan: ""
  slogan_en: ""
  web: ""
qq:
  app_id: xx
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  enable : false
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: Askanuo
  cdn: xx://xx.xx.com
  zone: xx
  size: "5"
email:
  host: smtp.qq.com
  port: 465
  user: xxx&qq.com
  password: xxx
  default_from_email: Askanuo
  use_ssl: false
  use_tls: true
jwt:
  secret: xxx
  expirse: 0
  issuer: xx
local:
  path: uploads/file
  store-path: uploads/file
